postgres:
  image: postgres:9.6.8
  container_name: nestjs_postgres
  ports:
    - "8001:5432"
  volumes:
    - postgres_data:/var/lib/postgresql
  environment:
    - POSTGRES_USER=demo
    - POSTGRES_PASSWORD=demo
    - POSTGRES_DB=demo
  restart: always 
redis:
  image: redis:4.0.8
  container_name: nestjs_redis
  ports:
    - "6379:6379"
  restart: always