postgres:
  image: postgres:9.6.8
  container_name: nestjs_postgres
  ports:
    - "8001:5432"
  volumes:
    - postgres_data:/var/lib/postgresql
  environment:
    - POSTGRES_USER=demo
    - POSTGRES_PASSWORD=demo
    - POSTGRES_DB=demo
  restart: always 
redis:
  image: redis:4.0.8
  container_name: nestjs_redis
  ports:
    - "6379:6379"
  restart: always
redis_pubsub:
  image: redis:4.0.8
  container_name: nestjs_redis_pubsub
  ports:
    - "6380:6379"
  restart: always
localstack:
  image: localstack/localstack
  container_name: nestjs_localstack
  ports:
    - '4572:4572'
    - '8081:8080'
  environment:
    - SERVICES=s3
    - DEFAULT_REGION=eu-central-1
    - DEBUG=1
    - DATA_DIR=/tmp/localstack/data
  volumes:
    - "/private/$TMPDIR:/tmp/localstack"
    - "/var/run/docker.sock:/var/run/docker.sock"