eventstore:
  image: eventstore/eventstore
  container_name: nestjs_eventstore
  ports:
    - 2113:2113
    - 1113:1113
  environment:
    - EVENTSTORE_RUN_PROJECTIONS=All
    - EVENTSTORE_START_STANDARD_PROJECTIONS=true