version: 2

jobs:
  backend_build:
    docker:
      - image: circleci/node:10.16.0
      - image: postgres:9.6.8
        command: postgres -p 8001
        environment:
          - POSTGRES_USER=demo
          - POSTGRES_PASSWORD=demo
          - POSTGRES_DB=demo

    working_directory: ~/nestjs-practise

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-server-{{ checksum "nestjs-1/yarn.lock" }}
            - v1-server-

      - run: 
          name: yarn install
          command: |
            cd nestjs-1
            yarn install

      - save_cache:
          paths:
            - nestjs-1/node_modules
            - ~/.cache/yarn
          key: v1-server-{{ checksum "nestjs-1/yarn.lock" }}
      
      - run: 
          name: Build
          command: |
            cd nestjs-1
            yarn tsc

      - run: 
          name: Wait for DB 
          command: dockerize -wait tcp://localhost:8001 -timeout 1m

      - run: 
          name: Tests
          command: |
            cd nestjs-1
            yarn test:sonar

      - run:
          name: Upload to CodeCov
          command: cd nestjs-1 && ./run.codecov.sh
      
      - persist_to_workspace:
          root: ~/nestjs-practise
          paths:
            - nestjs-1
          
  backend_sonar:
    docker: 
      - image: newtmitch/sonar-scanner
    
    working_directory: ~/nestjs-practise

    steps:
      - run: |
          cd /home
          mkdir circleci
          cd circleci
          mkdir nestjs-practise

      - attach_workspace:
          at: /home/circleci/nestjs-practise

      - run: |
          cd /home/circleci/nestjs-practise/nestjs-1
          ./run.sonar.sh
          
  backend_deploy:
    build: 
      machine: true 
    
    docker:
      - image: circleci/node:10.15.3

    working_directory: ~/nestjs-practise

    environment:
      HEROKU_APP: "nestjs-1"

    steps: 
      - checkout 
      
      - attach_workspace:
          at: /home/circleci/nestjs-practise
      
      #- setup_remote_docker
      
      - run: |

          cd /home/circleci/nestjs-practise
          wget "https://cli-assets.heroku.com/heroku-linux-x64.tar.gz"
          tar xzf heroku-linux-x64.tar.gz
          HEROKU="/home/circleci/nestjs-practise/heroku/bin/heroku"

          git pull https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master
          git subtree push --prefix nestjs-1 https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master -f

workflows:
  version: 2
  build_and_deploy: 
    jobs: 
      - backend_build
      - backend_sonar:
          requires:
            - backend_build
      - backend_deploy:
          filters:
            branches: 
              only: 
                - master
          requires:
            - backend_build