version: 2

jobs:
  backend_build:
    docker:
      - image: circleci/node:10.16.0
      - image: postgres:9.6.8
        command: postgres -p 8001
        environment:
          - POSTGRES_USER=demo
          - POSTGRES_PASSWORD=demo
          - POSTGRES_DB=demo

    working_directory: ~/nestjs-practise

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-server-{{ checksum "nestjs-1/yarn.lock" }}
            - v1-server-

      - run: 
          name: yarn install
          command: |
            cd nestjs-1
            yarn install

      - save_cache:
          paths:
            - nestjs-1/node_modules
            - ~/.cache/yarn
          key: v1-server-{{ checksum "nestjs-1/yarn.lock" }}
      
      - run: 
          name: Build
          command: |
            cd nestjs-1
            yarn tsc

      - run: 
          name: Wait for DB 
          command: dockerize -wait tcp://localhost:8001 -timeout 1m

      - run: 
          name: Tests
          command: |
            cd nestjs-1
            yarn test:e2e

workflows:
  version: 2
  build_only: 
    jobs: 
      - backend_build