version: 2

jobs:
  backend_build:
    docker:
      - image: circleci/node:10.16.0
      - image: postgres:9.6.8
        command: postgres -p 8001
        environment:
          - POSTGRES_USER=demo
          - POSTGRES_PASSWORD=demo
          - POSTGRES_DB=demo
      - image: redis:4.0.8
      - image: localstack/localstack:0.9.4
        environment:
          - SERVICES=s3
          - DEFAULT_REGION=eu-central-1

    working_directory: ~/nestjs-practise

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-server-{{ checksum "nestjs-1/yarn.lock" }}
            - v1-server-

      - run: 
          name: yarn install
          command: |
            cd nestjs-1
            yarn install

      - save_cache:
          paths:
            - nestjs-1/node_modules
            - ~/.cache/yarn
          key: v1-server-{{ checksum "nestjs-1/yarn.lock" }}
      
      - run: 
          name: Build
          command: |
            cd nestjs-1
            yarn tsc

      - run: 
          name: Wait for DB 
          command: dockerize -wait tcp://localhost:8001 -timeout 1m

      - run: 
          name: Creating S3 bucket for testing
          command: |
            cd nestjs-1
            ./run.s3.bucket.prepare.sh nestjs-local

      - run: 
          name: Tests
          command: |
            cd nestjs-1
            yarn test:sonar

      - run:
          name: Upload to CodeCov
          command: cd nestjs-1 && ./run.codecov.sh
      
      - persist_to_workspace:
          root: ~/nestjs-practise
          paths:
            - nestjs-1
          
  backend_sonar:
    docker: 
      - image: newtmitch/sonar-scanner
    
    working_directory: ~/nestjs-practise

    steps:
      - run: |
          cd /home
          mkdir circleci
          cd circleci
          mkdir nestjs-practise

      - attach_workspace:
          at: /home/circleci/nestjs-practise

      - run: |
          cd /home/circleci/nestjs-practise/nestjs-1
          ./run.sonar.sh
          
  backend_deploy:
    build: 
      machine: true 
    
    docker:
      - image: circleci/node:10.15.3

    working_directory: ~/nestjs-practise

    steps: 
      - checkout 
      
      - attach_workspace:
          at: /home/circleci/nestjs-practise
      
      - setup_remote_docker
      
      - run: 
          name: Deploying
          command: |

            cd /home/circleci/nestjs-practise
            wget "https://cli-assets.heroku.com/heroku-linux-x64.tar.gz"
            tar xzf heroku-linux-x64.tar.gz
            HEROKU="/home/circleci/nestjs-practise/heroku/bin/heroku"

            echo "Build docker"
            cd nestjs-1 && docker build -t nestjs_server .

            export HEROKU_APP=""
            [[ "${CIRCLE_BRANCH}" == "master" ]] && export HEROKU_APP="nestjs-1"
            [[ "${CIRCLE_BRANCH}" == "staging" ]] && export HEROKU_APP="staging-nestjs-1"

            if [[ ! -z "$HEROKU_APP" ]]; then

              echo "Will deploy to $HEROKU_APP"
              docker tag nestjs_server registry.heroku.com/$HEROKU_APP/web

              echo "container login"
              $HEROKU container:login

              echo "docker push"
              docker push registry.heroku.com/$HEROKU_APP/web
                
              echo "container release"
              $HEROKU container:release web 

            fi

workflows:
  version: 2
  build_and_deploy: 
    jobs: 
      - backend_build
      - backend_sonar:
          requires:
            - backend_build
      - backend_deploy:
          filters:
            branches: 
              only: 
                - master
                - staging
          requires:
            - backend_build