export enum RightsEnum {
  CAN_CREATE_USER = 'CAN_CREATE_USER',
  CAN_READ_USERS = 'CAN_READ_USERS',
  CAN_EDIT_USER = 'CAN_EDIT_USER',

  CAN_CREATE_TICKET = 'CAN_CREATE_TICKET',

  CAN_DO_RANDOM_STUFF = 'CAN_DO_RANDOM_STUFF',

  CAN_CREATE_INVOICE = 'CAN_CREATE_INVOICE',

  CAN_UPLOAD_USER_FILES = 'CAN_UPLOAD_USER_FILES',
}
