export const ChatConstants = {
  EVENT: {
    CHAT_HANDSHAKE_EVENT: 'CHAT_HANDSHAKE_EVENT',

    // PubSub
    PUBSUB_CHAT_HANDSHAKE_EVENT: 'PUBSUB_CHAT_HANDSHAKE_EVENT',
  },
  RESULT: {
    CHAT_HANDSHAKE_RESULT: 'CHAT_HANDSHAKE_RESULT',
    CHAT_JOIN_RESULT: 'CHAT_JOIN_RESULT',
    CHAT_MESSAGE_RESULT: 'CHAT_MESSAGE_RESULT',

    // PubSub
    PUBSUB_CHAT_HANDSHAKE_RESULT: 'PUBSUB_CHAT_HANDSHAKE_RESULT',
    PUBSUB_CHAT_JOIN_RESULT: 'PUBSUB_CHAT_JOIN_RESULT',
    PUBSUB_CHAT_MESSAGE_RESULT: 'PUBSUB_CHAT_MESSAGE_RESULT',
  },
};
