export const RedisConstants = {
  REDIS_CONNECTION: 'REDIS_CONNECTION',
  REDIS_PUBSUB_CONNECTION: 'REDIS_PUBSUB_CONNECTION',
  REDIS_SUB_CONNECTION: 'REDIS_SUB_CONNECTION',

  REDIS_DEMO_CHANNEL: 'REDIS_DEMO_CHANNEL',
};
